sftp.host=localhost
sftp.port=22
sftp.user=user
sftp.password=pass
sftp.remote-path=/remote/path
sftp.local-path=downloads
spring.datasource.url=jdbc:postgresql://localhost:5432/sftp
spring.datasource.username=sftp
spring.datasource.password=sftp
spring.jpa.hibernate.ddl-auto=update
